spring.datasource.url=jdbc:mysql://localhost:3306/aiinterview
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
gemini.api.key=AQ.Ab8RN6LTIBB8fG656uhjfWKjX5Ox5DvpUcDj8Citd0lNYJLwLw
